# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Docker Sign Attest Verify
description: Sign, attest and verify attestations
author: Docker

inputs:
  stage:
    required: true
    description: Stage of the build
  organization:
    required: true
    description: Namespace of the Docker organization
  image:
    required: true
    description: Image to analyze
  tags:
    required: true
    description: List of tags to add to the attestation
  file:
    required: false
    description: Build file


runs:
  using: node20
  main: index.js

branding:
  icon: shield
  color: gray-dark