name: build-push

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      tag: 
        required: true
        type: string
      file:
        required: true
        type: string
    secrets:
      docker_hub_user:
        required: true  
      docker_hub_password:
        required: true
      signing_key:
        required: true
      signing_key_passphrase:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3        

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_hub_user }}
          password: ${{ secrets.docker_hub_password }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha,prefix=
            type=raw,${{ inputs.tag }}
          images: ${{ inputs.name }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6     
        with:
          context: .
          file: ${{ inputs.file }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: generator=docker/scout-sbom-indexer:1
          platforms: linux/amd64,linux/arm64
          outputs: type=oci,dest=./oci,tar=false
      
      - name: Sign and attest Docker image
        id: sign-and-attest
        uses: cdupuis/dta-workflows@main
        with:
          image: ./oci
          tags: ${{ steps.meta.outputs.tags }}
          private-key: ${{ secrets.signing_key }}
          private-key-passphrase: ${{ secrets.signing_key_passphrase }}
          registry-user-name: ${{ secrets.docker_hub_user }}
          registry-password: ${{ secrets.docker_hub_password }}
          organization: ${{ secrets.docker_hub_user }}
