name: build-push

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      tag: 
        required: true
        type: string
      file:
        required: true
        type: string
    secrets:
      docker_hub_user:
        required: true  
      docker_hub_password:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3        

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_hub_user }}
          password: ${{ secrets.docker_hub_password }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=sha,prefix=
            type=raw,${{ inputs.tag }}
          images: ${{ inputs.name }}

      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v6     
        with:
          context: .
          file: ${{ inputs.file }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: generator=docker/scout-sbom-indexer:1
          platforms: linux/amd64,linux/arm64
          outputs: type=oci,dest=./oci,tar=false

      - name: Log into refrerrer registry
        uses: docker/login-action@v3
        with:
          registry: registry.scout.docker.com
          username: ${{ secrets.docker_hub_user }}
          password: ${{ secrets.docker_hub_password }}
      
      - name: Sign and attest Docker image
        id: sign-and-attest
        uses: cdupuis/dta-workflows@main
        with:
          state: sign-attest
          image: ./oci
          file: ${{ inputs.file }}
          tags: ${{ steps.meta.outputs.tags }}
          organization: ${{ secrets.docker_hub_user }}

      - name: Verify and attest Docker image
        id: verify-and-attest
        uses: cdupuis/dta-workflows@main
        with:
          state: verify-attest
          image: ${{ fromJson(steps.meta.outputs.json).tags[1] }}
          tags: ${{ fromJson(steps.meta.outputs.json).tags[0] }}
          organization: ${{ secrets.docker_hub_user }}
